### ISSUE TITLE
Stereo mode

### ISSUE THREAD

**Issue by elfredo** [arnaud-carre/StSound#5]
Hi Arnaud,

I was testing StSound from your website [http://leonard.oxg.free.fr/download/StSound_1_43.zip]. It seems this one plays YM files in stereo mode whereas the github StSoundLibrary only works in mono. 
Is there a way to enable it ?

Thank you

**Comment by arnaud-carre** [comment]
the old StSound player had some additional sound fx such as a fake stereo mode where the mono stream is just time delayed a bit between left / right. ( creating a cheap "spatial" effect).
YM2149 chip is a mono sound chip by nature. It's up to the user to add any sound fx over the ym2149 mono signal
